spring:
  datasource:
    url: jdbc:h2:mem:withmeal-db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: create

jwt:
  access_token_secretKey: ${JWT_ACCESS_KEY}
  access_token_valid_time: ${ACCESS_TOKEN_VALID_TIME}